### ISSUE TITLE
 description edittext  multiline

### ISSUE THREAD

**Issue by Pawan0411** [Pawan0411/Work-Scheduler#3]
At present, in worker Account activity and history section of user account 
**description editText is in single line make it to multiLine.**

**Comment by chydee** [comment]
I will take this up

**Comment by chydee** [comment]
Done. PR as been created. I also did some code clean up

**Comment by Pawan0411** [comment]
You need to do it for both the section 

1. History
2. Worker account

And work description is still in single line @chydee

**Comment by chydee** [comment]
Okay, I'll see to it

**Comment by Pawan0411** [comment]
fixed.

**Comment by chydee** [comment]
By me?

**Comment by sdzshn3** [comment]
Hey @chydee
We were using the TextInputEditText as a TextView because the layout of that edit texts looks good. So, we have made it non editable. But you have made it editable again. So i have fixed it by setFocusable(false); and setting the input type as textMultiLine.
Any how, Thanks a lot for contributing. We have more exciting tasks ahead.
